import { join } from 'node:path';

import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  reactStrictMode: true,
  // No external image host: product visuals are SVGs generated by the app itself,
  // so the suite stays deterministic and runs offline.
  poweredByHeader: false,
  // Traces the modules the server actually needs into `.next/standalone`, which
  // is what the production image ships — a few hundred megabytes of node_modules
  // never reach the runtime layer. Because this is a workspace, the traced tree
  // reproduces the monorepo layout: the entry point is `standalone/app/server.js`
  // and the dependencies sit at `standalone/node_modules`.
  output: 'standalone',
  // Without this, tracing starts at `app/` and misses the hoisted node_modules
  // one level up.
  outputFileTracingRoot: join(import.meta.dirname, '..'),
};

export default nextConfig;
