import { join } from 'node:path';

import type { NextConfig } from 'next';

/**
 * Standalone output is for the production image only, and is opted into by the
 * Dockerfile rather than always on.
 *
 * It traces the modules the server actually needs into `.next/standalone`, so a
 * few hundred megabytes of node_modules never reach the runtime layer. But a
 * build carrying it can no longer be served by `next start` — Next says so on
 * every boot — and `next start` is what Playwright's `webServer` and every CI
 * test job use. Leaving the warning in place would print "does not work" on
 * every single suite run, which is how a team learns to skim past warnings.
 *
 * The packaging is still exercised: the `deploiement` job in ci.yml builds the
 * real image and runs the whole stack against it on every push.
 */
const standalone = process.env.BUILD_STANDALONE === '1';

const nextConfig: NextConfig = {
  reactStrictMode: true,
  // No external image host: product visuals are SVGs generated by the app itself,
  // so the suite stays deterministic and runs offline.
  poweredByHeader: false,
  ...(standalone ? { output: 'standalone' as const } : {}),
  // Because this is a workspace, tracing has to start above `app/` or it misses
  // the hoisted node_modules. Harmless when standalone is off.
  outputFileTracingRoot: join(import.meta.dirname, '..'),
};

export default nextConfig;
